-- بوابة الفريق: مخطط Supabase آمن بدون الحاجة إلى Domain.
-- نفّذ هذا الملف مرة واحدة في Supabase SQL Editor.
-- بعد ذلك أنشئ أول حساب قائد من Authentication > Users ثم نفّذ قسم BOOTSTRAP بالأسفل.

create extension if not exists pgcrypto;
create extension if not exists citext;

drop table if exists public.requests cascade;
drop table if exists public.profiles cascade;
drop table if exists public.team_members cascade;
drop table if exists public.teams cascade;

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'فريق جديد',
  leader_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create table public.team_members (
  id bigint generated by default as identity primary key,
  team_id uuid not null references public.teams(id) on delete cascade,
  email citext not null,
  user_id uuid references auth.users(id) on delete set null,
  role text not null default 'employee' check (role in ('leader','employee')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(team_id,email)
);

create unique index team_members_user_team_unique on public.team_members(team_id,user_id) where user_id is not null;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete cascade,
  name text not null default '',
  role text not null default 'employee' check (role in ('leader','employee')),
  created_at timestamptz not null default now()
);

create table public.requests (
  id bigint generated by default as identity primary key,
  team_id uuid not null references public.teams(id) on delete cascade,
  requester_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  details text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected','completed')),
  created_at timestamptz not null default now()
);

create index requests_team_created_idx on public.requests(team_id,created_at desc);

alter table public.teams enable row level security;
alter table public.team_members enable row level security;
alter table public.profiles enable row level security;
alter table public.requests enable row level security;

-- Security-definer helpers avoid RLS recursion.
create or replace function public.is_team_leader(target_team uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and team_id=target_team and role='leader'); $$;

create or replace function public.is_team_member(target_team uuid)
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and team_id=target_team); $$;

-- بعد نجاح OTP، يربط المستخدم ببريد سبق أن أضافه القائد وينشئ ملفه.
create or replace function public.claim_membership()
returns boolean language plpgsql security definer set search_path = public
as $$
declare m public.team_members%rowtype; nm text;
begin
  select * into m from public.team_members where lower(email)=lower((select email from auth.users where id=auth.uid())) and active=true order by created_at limit 1;
  if not found then return false; end if;
  update public.team_members set user_id=auth.uid() where id=m.id;
  nm:=split_part((select email from auth.users where id=auth.uid()),'@',1);
  insert into public.profiles(id,team_id,name,role) values(auth.uid(),m.team_id,nm,m.role)
  on conflict(id) do update set team_id=excluded.team_id, role=excluded.role;
  return true;
end; $$;

grant execute on function public.claim_membership() to authenticated;

create policy teams_select_member on public.teams for select to authenticated using (id in (select team_id from public.profiles where id=auth.uid()));
create policy teams_update_leader on public.teams for update to authenticated using (leader_id=auth.uid()) with check (leader_id=auth.uid());

create policy members_select_same_team on public.team_members for select to authenticated using (public.is_team_member(team_id));
create policy members_insert_leader on public.team_members for insert to authenticated with check (public.is_team_leader(team_id) and role='employee');
create policy members_update_leader on public.team_members for update to authenticated using (public.is_team_leader(team_id)) with check (public.is_team_leader(team_id));

create policy profiles_select_same_team on public.profiles for select to authenticated using (public.is_team_member(team_id));
create policy profiles_update_self on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid() and team_id=(select team_id from public.profiles where id=auth.uid()));

create policy requests_select_own_or_leader on public.requests for select to authenticated using (requester_id=auth.uid() or public.is_team_leader(team_id));
create policy requests_insert_self on public.requests for insert to authenticated with check (requester_id=auth.uid() and public.is_team_member(team_id));
create policy requests_update_leader on public.requests for update to authenticated using (public.is_team_leader(team_id)) with check (public.is_team_leader(team_id));

-- BOOTSTRAP: بعد إنشاء أول مستخدم قائد من Authentication > Users،
-- ضع UUID الخاص به مكان YOUR_AUTH_USER_UUID ونفّذ هذا الجزء.
-- لا تضع Service Role Key داخل الموقع.
/*
insert into public.teams(id,name,leader_id) values(gen_random_uuid(),'فريقنا', 'YOUR_AUTH_USER_UUID') returning id;
-- انسخ team id الناتج في السطر التالي:
insert into public.team_members(team_id,email,user_id,role)
values('YOUR_TEAM_UUID','leader@example.com','YOUR_AUTH_USER_UUID','leader');
insert into public.profiles(id,team_id,name,role)
values('YOUR_AUTH_USER_UUID','YOUR_TEAM_UUID','قائد الفريق','leader');
*/

-- ملاحظة مهمة: في Authentication > URL Configuration أضف رابط Vercel/Netlify
-- إلى Site URL وRedirect URLs حتى يعمل OTP من الاستضافة المجانية.
