<resources>
    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:fontFamily">sans</item>
        <item name="android:colorAccent">#27856f</item>
        <item name="android:navigationBarColor">#f7f7f3</item>
        <item name="android:statusBarColor">#27856f</item>
        <item name="android:windowLightStatusBar">false</item>
    </style>
</resources>
